services:
  frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./app
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:  [ "yarn", "dev", "--debug" ]
