services:
  frontend:
    build:
      context: ./app/
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules


